language: php

matrix:
  fast_finish: true
  include:
    - php: '5.5'
      env: COMPOSER_PHPUNIT=false
    - php: '5.6'
      env: COMPOSER_PHPUNIT=false
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4snapshot'
    - php: 'nightly'
      env: IGNORE_PLATFORM_REQS=true
  allow_failures:
    - php: '5.5'
    - php: '5.6'
    - php: '7.0'
    - php: '7.4snapshot'
    - php: 'nightly'

addons:
 apt:
  packages:
   - ldap-utils
   - slapd
   # - php-ldap

install:
  - if [ "$COMPOSER_PHPUNIT" == 'false' ]; then composer remove phpunit/phpunit --dev; fi
  - if [ "$IGNORE_PLATFORM_REQS" == 'true' ]; then composer install --no-interaction --ignore-platform-reqs;
    else composer install --no-interaction;
    fi

before_script:
 - if [ "$COMPOSER_PHPUNIT" == 'false' ]; then phpunit --version; else vendor/bin/phpunit --version; fi
 - mkdir /tmp/slapd
 - sudo killall /usr/sbin/slapd
 - sudo slapd -f tests/slapd/slapd_standard.conf &
 - sleep 3
 - ldapadd -h localhost:389 -D cn=admin,dc=example,dc=com -w test -f tests/slapd/base.ldif
 - ldapadd -c -h localhost:389 -D cn=admin,dc=example,dc=com -w test -f tests/slapd/adtools_test_data.ldif

script:
 - if [ "$COMPOSER_PHPUNIT" == 'false' ]; then phpunit;
   else vendor/bin/phpunit;
   fi

after_script:
  - bash <(curl -s https://codecov.io/bash)