language: php

matrix:
  fast_finish: true
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4snapshot'
    - php: 'nightly'
      env: IGNORE_PLATFORM_REQS=true
  allow_failures:
    - php: '7.4snapshot'
    - php: 'nightly'

addons:
 apt:
  packages:
   - ldap-utils
   - slapd
   # - php-ldap

install:
  - if [ "$COMPOSER_PHPUNIT" == 'false' ]; then composer remove phpunit/phpunit --dev; fi
  - if [ "$IGNORE_PLATFORM_REQS" == 'true' ]; then composer install --no-interaction --ignore-platform-reqs;
    else composer install --no-interaction;
    fi

before_script:
 - if [ "$COMPOSER_PHPUNIT" == 'false' ]; then phpunit --version; else vendor/bin/phpunit --version; fi
 - mkdir /tmp/slapd
 - sudo killall /usr/sbin/slapd
 - php tests/slapd/build_config.php
 - sudo slapd -f tests/slapd/slapd.conf &

script:
 - if [ "$COMPOSER_PHPUNIT" == 'false' ]; then phpunit;
   else vendor/bin/phpunit;
   fi

after_script:
  - bash <(curl -s https://codecov.io/bash)