language: php

matrix:
  fast_finish: true
  include:
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
    - php: '8.0'
    - php: 'nightly'
    -  php: '7.4'
       name: 'Prefer lowest'
       install:
         - composer update --prefer-lowest
  allow_failures:
    - php: 'nightly'

addons:
  apt:
    packages:
      - ldap-utils
      - slapd

env:
  global:
    - XDEBUG_MODE=coverage

cache:
  directories:
    - $HOME/.cache/composer/files

install:
  - composer install --no-interaction

before_script:
  - vendor/bin/phpunit --version
  - mkdir /tmp/slapd
  - sudo killall /usr/sbin/slapd
  - php tests/slapd/build_config.php
  - sudo slapd -f tests/slapd/slapd.conf &
  - sleep 3

script:
  - vendor/bin/phpunit

after_script:
  - bash <(curl -s https://codecov.io/bash)