name: PHP Composer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.3', '7.4', '8.0', '8.1', '8.2' ]

    steps:
      - name: Build docker container
        uses: StorFollo-IKT/slapd-ad-emulator@master

      - uses: actions/checkout@v4

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: ldap, gettext

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check path
        run: |
          pwd
          ls -l vendor



      - name: Start docker container
        run: docker run -d -p 389:389 ad_emulator

      - name: Install LDAP utils
        run: sudo apt-get install -y ldap-utils

      - name: Run test suite
        run: |
          pwd
          ls -l vendor
          vendor/bin/phpunit