name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0' ]

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          extensions: ldap, gettext

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install LDAP
        run: |
          docker build -t adtools_php_ldap tests
          docker run -p 389:389 adtools_php_ldap -d
          sudo apt-get install -y ldap-utils

      - name: Setup LDAP
        run: |
          mkdir /tmp/slapd
          sudo killall /usr/sbin/slapd
          php tests/slapd/build_config.php
          sudo slapd -f tests/slapd/slapd.conf &
          sleep 3

      - name: Run test suite
        run: vendor/bin/phpunit